# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
          redis:
            image: redis:6.2-alpine
            ports:
              - "6379:6379"
          postgres:
            image: postgres:11-bullseye
            ports:
              - "5432:5432"
            env:
              POSTGRES_DB: rails_test
              POSTGRES_USER: rails
              POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Precompile assets
      run: bundle exec rake assets:precompile
    - name: Run Tests 
      run: bundle exec rake

  
    